# Generated by Django 5.2.17 on 2026-09-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_year', 'institution'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('spotify_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
    ]
