# Generated by Django 5.2.17 on 2026-09-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_portfolio_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('award', models.CharField(max_length=150)),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('organization', 'Organization'), ('event', 'Event'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance')], default='part-time', max_length=50),
        ),
    ]
