# Generated by Django 5.2.17 on 2026-09-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_clean_experience_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='organizer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
